SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `DB_SAUDE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DB_SAUDE` ;

-- -----------------------------------------------------
-- Table `DB_SAUDE`.`TAB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SAUDE`.`TAB_USUARIO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `RAZAO` VARCHAR(50) NOT NULL,
  `CNPJ` CHAR(20) NOT NULL,
  `FONE` CHAR(20) NULL,
  `RESPONSAVEL` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `USUARIO` CHAR(10) NOT NULL,
  `SENHA` CHAR(20) NOT NULL,
  `DATA_CADASTRO` TIMESTAMP NOT NULL,
  `STATUS` ENUM('A','I') NOT NULL DEFAULT 'A',
  PRIMARY KEY (`ID_USUARIO`, `RESPONSAVEL`),
  UNIQUE INDEX `USUARIO_UNIQUE` (`USUARIO` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SAUDE`.`TAB_IMPORTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SAUDE`.`TAB_IMPORTACAO` (
  `ID_IMPORTACAO` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL,
  `DATA_IMPORTACAO` TIMESTAMP NOT NULL,
  `QTDE_REGISTRO` MEDIUMINT NOT NULL,
  PRIMARY KEY (`ID_IMPORTACAO`),
  INDEX `fk_TAB_IMPORTACAO_TAB_USUARIO1_idx` (`ID_USUARIO` ASC),
  CONSTRAINT `FK_ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `DB_SAUDE`.`TAB_USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_SAUDE`.`TAB_PLANILHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_SAUDE`.`TAB_PLANILHA` (
  `ID_PLANILHA` INT NOT NULL AUTO_INCREMENT,
  `ID_IMPORTACAO` INT NOT NULL,
  `PATOLOGIA` VARCHAR(30) NOT NULL,
  `FAIXA_ETARIA` CHAR(6) NOT NULL,
  `SEXO` CHAR(1) NOT NULL,
  `QTDE_D` MEDIUMINT NOT NULL DEFAULT 0,
  `QTDE_S` MEDIUMINT NOT NULL DEFAULT 0,
  `QTDE_N` MEDIUMINT NOT NULL DEFAULT 0,
  `QTDE_T` MEDIUMINT NOT NULL DEFAULT 0,
  `DATA` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID_PLANILHA`),
  INDEX `FK_ID_IMPORTACAO_IDX` (`ID_IMPORTACAO` ASC),
  CONSTRAINT `FK_ID_IMPORTACAO`
    FOREIGN KEY (`ID_IMPORTACAO`)
    REFERENCES `DB_SAUDE`.`TAB_IMPORTACAO` (`ID_IMPORTACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

